from __future__ import annotations

import asyncio
import json
import os
import re
import shutil
import tempfile
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from fastapi import APIRouter, HTTPException, Query, UploadFile, File
from fastapi.responses import FileResponse
from pydantic import BaseModel

from common.webux.base import WebuxPluginManifest
from common.core.config import load_tool_config, save_tool_config

router = APIRouter()

# ── Pipeline state ────────────────────────────────────────────────────────────

STEP_NAMES = [
    "Remove silence",
    "Extract transcript",
    "Burn subtitles",
    "Generate title & description",
    "Upload to YouTube",
]

DEFAULT_VIDEO_SOURCE_PATH = "/home/joriel/Vidéos"
DEFAULT_VIDEO_EXTENSIONS = "mp4,mkv"

# Files generated by the pipeline — excluded from source selection
_INTERMEDIATE_RE = re.compile(r"_(nosilence|subtitled)$", re.IGNORECASE)


def _is_intermediate(path: Path) -> bool:
    return bool(_INTERMEDIATE_RE.search(path.stem))


@dataclass
class Step:
    name: str
    status: str = "pending"   # pending | running | done | error | skipped
    output: str = ""
    progress: float | None = None  # 0-100 when available
    start_time: float | None = None
    end_time: float | None = None


@dataclass
class Job:
    job_id: str
    source: str
    prompt_title: str
    prompt_summary: str
    do_remove_silence: bool
    do_burn_subtitles: bool
    simple_transcript: bool
    language: str
    model: str
    privacy: str
    description_prefix: str = ""
    source_urls: list[str] = field(default_factory=list)
    steps: list[Step] = field(default_factory=list)
    files: dict[str, str] = field(default_factory=dict)
    title: str = ""
    description: str = ""
    status: str = "running"
    video_url: str = ""
    studio_url: str = ""
    start_time: float = field(default_factory=time.time)
    end_time: float | None = None

    def to_dict(self) -> dict[str, Any]:
        now = time.time()
        job_elapsed = (self.end_time - self.start_time) if self.end_time else (now - self.start_time)
        return {
            "job_id": self.job_id,
            "status": self.status,
            "video_url": self.video_url,
            "studio_url": self.studio_url,
            "title": self.title,
            "description": self.description,
            "files": self.files,
            "start_time": self.start_time,
            "elapsed_seconds": round(job_elapsed, 1),
            "steps": [
                {
                    "name": s.name,
                    "status": s.status,
                    "output": s.output,
                    "progress": s.progress,
                    "start_time": s.start_time,
                    "elapsed_seconds": (
                        round(s.end_time - s.start_time, 1) if s.start_time and s.end_time
                        else round(now - s.start_time, 1) if s.start_time
                        else None
                    ),
                    "output_files": [
                        {"path": self.files[k], "name": Path(self.files[k]).name}
                        for k in _STEP_FILE_KEYS[i]
                        if k in self.files and self.files[k]
                    ],
                }
                for i, s in enumerate(self.steps)
            ],
        }


_jobs: dict[str, Job] = {}

# Files produced by each step (step index → list of job.files keys)
_STEP_FILE_KEYS: list[list[str]] = [
    ["no_silence"],
    ["transcript", "transcript_txt"],
    ["subtitled"],
    [],
    [],
]


# ── Config helpers ────────────────────────────────────────────────────────────

def _load_publish_cfg() -> dict:
    try:
        cfg = load_tool_config("youtube")
        return cfg.get("youtube", {}).get("publish", {})
    except Exception:
        return {}


def _save_publish_cfg(pub: dict) -> None:
    try:
        cfg = load_tool_config("youtube")
        yt = cfg.setdefault("youtube", {})
        yt["publish"] = pub
        save_tool_config("youtube", cfg)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to save config: {exc}")


# ── Meta persistence ──────────────────────────────────────────────────────────

def _meta_path(source: str) -> Path:
    p = Path(source)
    return p.parent / f"{p.stem}-meta.json"


def _save_meta(job: Job) -> None:
    meta: dict = {
        "source": job.source,
        "completed_steps": [i for i, s in enumerate(job.steps) if s.status == "done"],
        "skipped_steps": [i for i, s in enumerate(job.steps) if s.status == "skipped"],
        "files": job.files,
    }
    if job.title:
        meta["title"] = job.title
    if job.description:
        meta["description"] = job.description
    if job.source_urls:
        meta["source_urls"] = job.source_urls
    try:
        with open(_meta_path(job.source), "w", encoding="utf-8") as f:
            json.dump(meta, f, ensure_ascii=False, indent=2)
    except Exception:
        pass


def _load_meta(source: str) -> dict:
    try:
        p = _meta_path(source)
        if p.exists():
            with open(p, encoding="utf-8") as f:
                return json.load(f)
    except Exception:
        pass
    return {}


# ── Helpers ───────────────────────────────────────────────────────────────────

def _yt() -> str:
    return shutil.which("youtube") or "youtube"


def _pr() -> str:
    return shutil.which("prompt") or "prompt"


def _stem(p: str) -> str:
    return Path(p).stem


def _dir(p: str) -> Path:
    return Path(p).resolve().parent


def _extract_video_id(url: str) -> str:
    m = re.search(r"[?&]v=([a-zA-Z0-9_-]+)", url)
    return m.group(1) if m else ""


def _ass_to_plain_text(ass_path: str) -> str:
    lines = []
    with open(ass_path, encoding="utf-8") as f:
        for line in f:
            if not line.startswith("Dialogue:"):
                continue
            parts = line.split(",", 9)
            if len(parts) < 10:
                continue
            text = parts[9].strip()
            text = re.sub(r"\{[^}]*\}", "", text)
            if text:
                lines.append(text)
    return "\n".join(lines)


def _get_video_duration(path: str) -> float:
    import subprocess
    result = subprocess.run(
        [
            "ffprobe", "-v", "quiet",
            "-show_entries", "format=duration",
            "-of", "default=noprint_wrappers=1:nokey=1",
            path,
        ],
        capture_output=True, text=True,
    )
    try:
        return float(result.stdout.strip())
    except ValueError:
        return 0.0


def _sanitize_filename(title: str) -> str:
    safe = re.sub(r'[<>:"/\\|?*\n\r\t]', '', title)
    safe = re.sub(r'\s+', '_', safe.strip())
    safe = safe.strip('._')
    return safe[:100] if safe else "video"


def _validate_urls(urls: list[str]) -> list[str]:
    result = []
    for u in urls:
        u = u.strip()
        if u and (u.startswith("http://") or u.startswith("https://")):
            result.append(u)
    return result


async def _run(step: Step, *cmd: str) -> tuple[int, str]:
    proc = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()
    out = stdout.decode(errors="replace").strip()
    err = stderr.decode(errors="replace").strip()
    step.output = (out + "\n" + err).strip()
    return proc.returncode or 0, out


# Direct function imports for progress-capable execution
try:
    from commands.remove_silence.register import remove_silence_simple
except Exception:
    remove_silence_simple = None

try:
    from commands.burn_subtitles.register import burn_ass_subtitles
except Exception:
    burn_ass_subtitles = None

try:
    from commands.extract_transcript.register import (
        generate_karaoke_ass,
        transcribe_to_srt,
        transcribe_to_txt,
    )
except Exception:
    generate_karaoke_ass = transcribe_to_srt = transcribe_to_txt = None


# ── Pipeline ──────────────────────────────────────────────────────────────────

async def _run_pipeline_from(job: Job, from_step: int) -> None:
    """Unified pipeline runner. from_step is the first step to execute; earlier steps are skipped."""
    stem = _stem(job.source)
    pub_cfg = _load_publish_cfg()
    d = Path(pub_cfg.get("video_source_path", DEFAULT_VIDEO_SOURCE_PATH)).expanduser().resolve()

    # Mark steps before from_step as skipped if still pending
    for i in range(from_step):
        if job.steps[i].status == "pending":
            job.steps[i].status = "skipped"

    # Determine current_video starting point from available prior artifacts
    current_video = job.source

    # ── Step 0 — Remove silence ───────────────────────────────────────────────
    if from_step <= 0:
        s0 = job.steps[0]
        if job.do_remove_silence:
            s0.start_time = time.time()
            s0.status = "running"
            s0.progress = 0.0  # show bar immediately while moviepy loads
            out_path = str(d / f"{stem}_nosilence.mp4")
            if remove_silence_simple is not None:
                def _prog0(pct, _): s0.progress = round(pct, 1)
                try:
                    await asyncio.to_thread(remove_silence_simple, job.source, out_path, -65.0, _prog0)
                    rc = 0
                except Exception as exc:
                    s0.output = str(exc); rc = 1
            else:
                rc, _ = await _run(s0, _yt(), "remove-silence", job.source, "-o", out_path)
            if rc != 0:
                s0.end_time = time.time(); s0.status = "error"; job.status = "error"; _save_meta(job); return
            duration = _get_video_duration(out_path)
            if duration > 180:
                s0.end_time = time.time(); s0.status = "error"
                s0.output += f"\n⏱ Video is {duration:.0f}s — exceeds 180s limit for YouTube Shorts."
                job.status = "error"; _save_meta(job); return
            s0.end_time = time.time(); s0.status = "done"; s0.progress = 100
            s0.output += f"\n⏱ Duration: {duration:.0f}s"
            current_video = out_path
            job.files["no_silence"] = out_path
        else:
            s0.status = "skipped"
        _save_meta(job)
    else:
        nv = job.files.get("no_silence", "")
        if nv and Path(nv).exists():
            current_video = nv

    # ── Step 1 — Extract transcript ───────────────────────────────────────────
    ass_path = str(d / f"{stem}.ass")
    txt_path = str(d / f"{stem}_transcript.txt")

    if from_step <= 1:
        s1 = job.steps[1]
        s1.start_time = time.time()
        s1.status = "running"
        s1.progress = 0.0  # bar appears immediately

        if generate_karaoke_ass is not None:
            if job.simple_transcript:
                # Simple mode: no estimator, no concurrent task — pure blocking thread.
                # The elapsed step-timer in the UI is the only feedback.
                # Use this to measure the true baseline transcription time.
                try:
                    await asyncio.to_thread(
                        generate_karaoke_ass, current_video, ass_path,
                        job.language, job.model, 96, 35, None,
                    )
                    rc = 0
                except Exception as exc:
                    s1.output = str(exc); rc = 1
            else:
                # Advanced mode: concurrent estimator loop keeps the bar moving even
                # when faster-whisper is silent for several minutes between windows.
                s1.progress = 0.0

                def _prog1(pct, _):
                    if pct > (s1.progress or 0):
                        s1.progress = round(pct, 1)

                video_dur = _get_video_duration(current_video)
                expected_secs = max(video_dur * 7, 60)

                t1_task = asyncio.create_task(
                    asyncio.to_thread(
                        generate_karaoke_ass, current_video, ass_path,
                        job.language, job.model, 96, 35, _prog1,
                    )
                )
                t1_start = time.time()
                while not t1_task.done():
                    elapsed = time.time() - t1_start
                    est_pct = min(90.0, elapsed / expected_secs * 100)
                    if est_pct > (s1.progress or 0):
                        s1.progress = round(est_pct, 1)
                    await asyncio.sleep(3)

                try:
                    await t1_task
                    rc = 0
                except Exception as exc:
                    s1.output = str(exc); rc = 1
        else:
            rc, _ = await _run(
                s1, _yt(), "extract-transcript", current_video,
                "-o", ass_path, "-l", job.language, "-m", job.model,
            )
        if rc != 0:
            s1.end_time = time.time(); s1.status = "error"; job.status = "error"; _save_meta(job); return
        s1.end_time = time.time()
        elapsed_s = round(s1.end_time - s1.start_time, 1)
        mode_label = "simple" if job.simple_transcript else "advanced"
        s1.output = f"Done in {elapsed_s}s [{mode_label} mode]"
        s1.status = "done"; s1.progress = 100
        plain = _ass_to_plain_text(ass_path)
        with open(txt_path, "w", encoding="utf-8") as _f:
            _f.write(plain)
        job.files["transcript"] = ass_path
        job.files["transcript_txt"] = txt_path
        _save_meta(job)
    else:
        ass_path = job.files.get("transcript") or ass_path
        txt_path = job.files.get("transcript_txt") or txt_path
        if not Path(txt_path).exists() and Path(ass_path).exists():
            plain = _ass_to_plain_text(ass_path)
            with open(txt_path, "w", encoding="utf-8") as _f:
                _f.write(plain)

    # ── Step 2 — Burn subtitles ───────────────────────────────────────────────
    if from_step <= 2:
        s2 = job.steps[2]
        if job.do_burn_subtitles:
            s2.start_time = time.time()
            s2.status = "running"
            out_path = str(d / f"{stem}_subtitled.mp4")
            if burn_ass_subtitles is not None:
                def _prog2(pct, _): s2.progress = pct
                try:
                    await asyncio.to_thread(burn_ass_subtitles, current_video, ass_path, out_path, 96, _prog2)
                    rc = 0
                except Exception as exc:
                    s2.output = str(exc); rc = 1
            else:
                rc, _ = await _run(
                    s2, _yt(), "burn-subtitles", current_video, ass_path, "-o", out_path
                )
            if rc != 0:
                s2.end_time = time.time(); s2.status = "error"; job.status = "error"; _save_meta(job); return
            s2.end_time = time.time(); s2.status = "done"; s2.progress = 100
            current_video = out_path
            job.files["subtitled"] = out_path
        else:
            s2.status = "skipped"
        _save_meta(job)
    else:
        sv = job.files.get("subtitled", "")
        if sv and Path(sv).exists():
            current_video = sv

    job.files["final_video"] = current_video
    await _run_llm_and_upload(job, txt_path, current_video, from_step)


async def _run_llm_and_upload(job: Job, transcript_path: str, final_video: str, from_step: int = 3) -> None:
    pub_cfg = _load_publish_cfg()

    # ── Step 3 — Generate title & description ─────────────────────────────────
    if from_step <= 3:
        s3 = job.steps[3]
        s3.start_time = time.time()
        s3.status = "running"

        rc, title_out = await _run(s3, _pr(), "apply", job.prompt_title, f"transcript=@{transcript_path}")
        if rc != 0:
            s3.end_time = time.time(); s3.status = "error"; job.status = "error"; _save_meta(job); return

        proc = await asyncio.create_subprocess_exec(
            _pr(), "apply", job.prompt_summary, f"transcript=@{transcript_path}",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        desc_out, desc_err = await proc.communicate()
        if proc.returncode:
            s3.output += "\n" + desc_err.decode(errors="replace")
            s3.end_time = time.time(); s3.status = "error"; job.status = "error"; _save_meta(job); return

        raw_description = desc_out.decode(errors="replace").strip()
        signature = pub_cfg.get("signature", "").strip()
        parts = []
        if job.description_prefix.strip():
            parts.append(job.description_prefix.strip())
        parts.append(raw_description)
        if signature:
            parts.append(signature)
        job.title = title_out.strip()
        job.description = "\n\n".join(parts)

        # Rename final video using sanitized title
        safe_name = _sanitize_filename(job.title)
        ext = Path(final_video).suffix or ".mp4"
        renamed_path = str(Path(final_video).parent / f"{safe_name}{ext}")
        if Path(final_video).resolve() != Path(renamed_path).resolve():
            if not Path(renamed_path).exists():
                os.rename(final_video, renamed_path)
            final_video = renamed_path
            job.files["final_video"] = final_video

        s3.output = f"Title: {job.title[:80]}"
        s3.end_time = time.time(); s3.status = "done"
        _save_meta(job)
    else:
        job.steps[3].status = "skipped"
        # job.title / job.description already loaded from meta by the resume endpoint

    # ── Step 4 — Upload ───────────────────────────────────────────────────────
    s4 = job.steps[4]
    s4.start_time = time.time()
    s4.status = "running"
    rc, url_out = await _run(
        s4, _yt(), "upload", final_video,
        "--title", job.title,
        "--description", job.description,
        "--privacy", job.privacy,
    )
    if rc != 0:
        s4.end_time = time.time(); s4.status = "error"; job.status = "error"; _save_meta(job); return

    s4.end_time = time.time(); s4.status = "done"
    watch_url = url_out.strip()
    video_id = _extract_video_id(watch_url)
    if video_id:
        job.video_url = f"https://www.youtube.com/shorts/{video_id}"
        job.studio_url = f"https://studio.youtube.com/video/{video_id}/edit"
    else:
        job.video_url = watch_url
        job.studio_url = ""
    job.end_time = time.time()
    job.status = "done"
    _save_meta(job)

    post_script = pub_cfg.get("post_publish_script", "").strip()
    if post_script and Path(post_script).is_file():
        await asyncio.create_subprocess_exec(
            "bash", post_script, final_video,
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL,
        )


# ── Config API ────────────────────────────────────────────────────────────────

@router.get("/config")
async def get_config():
    pub = _load_publish_cfg()
    return {
        "video_source_path": pub.get("video_source_path", DEFAULT_VIDEO_SOURCE_PATH),
        "video_extensions": pub.get("video_extensions", DEFAULT_VIDEO_EXTENSIONS),
        "signature": pub.get("signature", ""),
        "post_publish_script": pub.get("post_publish_script", ""),
    }


class ConfigSaveRequest(BaseModel):
    video_source_path: str = DEFAULT_VIDEO_SOURCE_PATH
    video_extensions: str = DEFAULT_VIDEO_EXTENSIONS
    signature: str = ""
    post_publish_script: str = ""


@router.post("/config")
async def save_config(req: ConfigSaveRequest):
    pub = _load_publish_cfg()
    pub["video_source_path"] = req.video_source_path
    pub["video_extensions"] = req.video_extensions
    pub["signature"] = req.signature
    pub["post_publish_script"] = req.post_publish_script
    _save_publish_cfg(pub)
    return {"ok": True}


# ── Video list API ────────────────────────────────────────────────────────────

@router.get("/list-videos")
async def list_videos(
    path: str = Query(default=DEFAULT_VIDEO_SOURCE_PATH),
    extensions: str = Query(default=DEFAULT_VIDEO_EXTENSIONS),
):
    d = Path(path).expanduser()
    if not d.exists() or not d.is_dir():
        return {"videos": [], "error": f"Directory not found: {path}"}
    exts = {("." + e.strip().lstrip(".")).lower() for e in extensions.split(",") if e.strip()}
    files = sorted(
        [f for f in d.iterdir() if f.suffix.lower() in exts and not _is_intermediate(f)],
        key=lambda f: f.stat().st_mtime,
        reverse=True,
    )
    return {
        "videos": [
            {"name": f.name, "path": str(f), "mtime": f.stat().st_mtime}
            for f in files
        ]
    }


# ── Prompt list API ───────────────────────────────────────────────────────────

@router.get("/list-prompts")
async def list_prompts():
    pr = _pr()
    proc = await asyncio.create_subprocess_exec(
        pr, "list", "--names-only",
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, _ = await proc.communicate()
    names = [n.strip() for n in stdout.decode(errors="replace").splitlines() if n.strip()]
    return {"prompts": names}


# ── Video preview API ─────────────────────────────────────────────────────────

_MIME = {
    ".mp4": "video/mp4",
    ".mkv": "video/x-matroska",
    ".mov": "video/quicktime",
    ".webm": "video/webm",
}

@router.get("/video-preview")
async def video_preview(file: str = Query(...)):
    p = Path(file).expanduser().resolve()
    if not p.exists():
        raise HTTPException(status_code=404, detail="Video not found")
    mime = _MIME.get(p.suffix.lower(), "video/mp4")
    return FileResponse(str(p), media_type=mime)


@router.get("/download")
async def download_file(file: str = Query(...)):
    p = Path(file).expanduser().resolve()
    if not p.exists():
        raise HTTPException(status_code=404, detail="File not found")
    return FileResponse(str(p), filename=p.name)


@router.post("/upload-external")
async def upload_external(file: UploadFile = File(...)):
    if not file.filename:
        raise HTTPException(status_code=400, detail="No file provided")
    ext = Path(file.filename).suffix.lower()
    if ext not in {".mp4", ".mkv", ".mov", ".webm"}:
        raise HTTPException(status_code=400, detail="Unsupported video format")
    pub_cfg = _load_publish_cfg()
    source_dir = Path(pub_cfg.get("video_source_path", DEFAULT_VIDEO_SOURCE_PATH)).expanduser()
    source_dir.mkdir(parents=True, exist_ok=True)
    stem = Path(file.filename).stem
    dest = source_dir / f"{stem}{ext}"
    if dest.exists():
        dest = source_dir / f"{stem}_{uuid.uuid4().hex[:8]}{ext}"
    with open(dest, "wb") as f:
        f.write(await file.read())
    return {"path": str(dest), "name": file.filename}


# ── Job API ───────────────────────────────────────────────────────────────────

class StartRequest(BaseModel):
    source: str
    prompt_title: str
    prompt_summary: str
    do_remove_silence: bool = True
    do_burn_subtitles: bool = True
    simple_transcript: bool = True
    language: str = "fr"
    model: str = "medium"
    privacy: str = "unlisted"
    description_prefix: str = ""
    source_urls: list[str] = []


class ResumeRequest(BaseModel):
    source: str
    prompt_title: str
    prompt_summary: str
    from_step: int = 3          # first step to execute; earlier steps use cached artifacts
    do_burn_subtitles: bool = True
    simple_transcript: bool = True
    language: str = "fr"
    model: str = "medium"
    privacy: str = "unlisted"
    description_prefix: str = ""
    source_urls: list[str] = []


@router.post("/start")
async def start(req: StartRequest):
    source = str(Path(req.source).expanduser().resolve())
    if not Path(source).exists():
        raise HTTPException(status_code=400, detail=f"File not found: {source}")

    job_id = str(uuid.uuid4())
    job = Job(
        job_id=job_id,
        source=source,
        prompt_title=req.prompt_title,
        prompt_summary=req.prompt_summary,
        do_remove_silence=req.do_remove_silence,
        do_burn_subtitles=req.do_burn_subtitles,
        simple_transcript=req.simple_transcript,
        language=req.language,
        model=req.model,
        privacy=req.privacy,
        description_prefix=req.description_prefix,
        source_urls=_validate_urls(req.source_urls),
        steps=[Step(name=n) for n in STEP_NAMES],
    )
    _jobs[job_id] = job
    asyncio.create_task(_run_pipeline_from(job, 0))
    return {"job_id": job_id}


@router.get("/status/{job_id}")
async def status(job_id: str):
    job = _jobs.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    return job.to_dict()


@router.post("/resume")
async def resume(req: ResumeRequest):
    source = str(Path(req.source).expanduser().resolve())
    if not Path(source).exists():
        raise HTTPException(status_code=400, detail=f"File not found: {source}")

    meta = _load_meta(source)
    files = dict(meta.get("files", {}))

    from_step = max(1, min(req.from_step, len(STEP_NAMES) - 1))

    # Validate required artifacts exist for the requested entry point
    if from_step >= 2:
        ass = files.get("transcript", "")
        if not ass or not Path(ass).exists():
            raise HTTPException(status_code=400, detail="Transcript (.ass) not found; cannot resume from step 2+")
    if from_step >= 3:
        txt = files.get("transcript_txt", "")
        if not txt or not Path(txt).exists():
            ass = files.get("transcript", "")
            if ass and Path(ass).exists():
                stem = _stem(source)
                txt_path = str(Path(source).parent / f"{stem}_transcript.txt")
                plain = _ass_to_plain_text(ass)
                with open(txt_path, "w", encoding="utf-8") as _f:
                    _f.write(plain)
                files["transcript_txt"] = txt_path
            else:
                raise HTTPException(status_code=400, detail="Transcript text not found; cannot resume from step 3+")

    completed_before = set(meta.get("completed_steps", []))
    skipped_before = set(meta.get("skipped_steps", []))

    job_id = str(uuid.uuid4())
    job = Job(
        job_id=job_id,
        source=source,
        prompt_title=req.prompt_title,
        prompt_summary=req.prompt_summary,
        do_remove_silence=False,
        do_burn_subtitles=req.do_burn_subtitles,
        simple_transcript=req.simple_transcript,
        language=req.language,
        model=req.model,
        privacy=req.privacy,
        description_prefix=req.description_prefix,
        source_urls=_validate_urls(req.source_urls),
        steps=[Step(name=n) for n in STEP_NAMES],
        files=files,
        title=meta.get("title", ""),
        description=meta.get("description", ""),
    )
    for i in completed_before:
        if i < from_step:
            job.steps[i].status = "done"
    for i in skipped_before:
        if i < from_step:
            job.steps[i].status = "skipped"

    _jobs[job_id] = job
    asyncio.create_task(_run_pipeline_from(job, from_step))
    return {"job_id": job_id}


@router.post("/check-resume")
async def check_resume(body: dict):
    source = str(Path(body.get("source", "")).expanduser().resolve())
    meta = _load_meta(source)
    completed = set(meta.get("completed_steps", []))
    skipped = set(meta.get("skipped_steps", []))
    passed = completed | skipped
    available = sorted({c + 1 for c in passed if c + 1 < len(STEP_NAMES)})
    files = meta.get("files", {})
    step_files = [
        [
            {"path": files[k], "name": Path(files[k]).name}
            for k in keys
            if k in files and files[k] and Path(files[k]).exists()
        ]
        for keys in _STEP_FILE_KEYS
    ]
    return {
        "can_resume": bool(available),
        "available_from_steps": available,
        "completed_steps": sorted(completed),
        "skipped_steps": sorted(skipped),
        "step_files": step_files,
    }


# ── Frontend ──────────────────────────────────────────────────────────────────

_HTML = """<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Publish</title>
  <style>
    :root {
      --bg:#1a1a2e; --bg2:#16213e; --text:#eee; --dim:#888;
      --accent:#0f3460; --ok:#4ade80; --err:#f87171; --warn:#fbbf24; --border:#333;
      --link:#7dd3fc;
    }
    body { margin:0; padding:16px; background:var(--bg); color:var(--text);
           font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; }
    .wrap { max-width:860px; margin:0 auto; }
    h2 { margin:0 0 12px; font-size:18px; }
    label { display:block; font-size:12px; color:var(--dim); margin-bottom:3px; }
    input[type=text], select, textarea {
      width:100%; padding:7px 10px; border:1px solid var(--border);
      background:var(--bg2); color:var(--text); border-radius:6px;
      box-sizing:border-box; font-size:13px;
    }
    textarea { resize:vertical; }
    .row { margin-bottom:10px; }
    .cols2 { display:flex; gap:12px; }
    .cols2 .row { flex:1; }
    .checkrow { display:flex; align-items:center; gap:8px; margin-bottom:6px; font-size:13px; }
    button { padding:7px 14px; border:none; border-radius:6px; cursor:pointer; font-size:13px; font-weight:600; }
    .btn-go     { background:var(--ok); color:#000; }
    .btn-go:hover { opacity:.88; }
    .btn-go:disabled { opacity:.4; cursor:default; }
    .btn-resume { background:var(--warn); color:#000; }
    .btn-resume:hover { opacity:.88; }
    .btn-resume:disabled { opacity:.4; cursor:default; }
    .btn-sec    { background:var(--accent); color:var(--text); }
    .btn-sec:hover { opacity:.88; }
    /* two-column main layout */
    .main-layout { display:flex; gap:16px; align-items:flex-start; }
    .main-left { flex:1; min-width:0; }
    .main-right { flex:0 0 260px; }
    .video-wrap { border:1px solid var(--border); border-radius:8px; overflow:hidden;
                  background:#000; display:none; }
    .video-wrap video { width:100%; height:220px; object-fit:contain; display:block; }
    .video-name { font-size:11px; color:var(--dim); padding:4px 8px;
                  background:var(--bg2); white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }
    /* pipeline */
    .steps { margin:14px 0 10px; }
    .step { display:flex; align-items:flex-start; gap:10px; padding:6px 0;
            border-bottom:1px solid var(--border); font-size:13px; }
    .step:last-child { border-bottom:none; }
    .step-icon { width:20px; flex-shrink:0; font-size:14px; margin-top:1px; }
    .step-name { flex:1; }
    .step-progress { width:120px; height:6px; margin-left:8px; vertical-align:middle; }
    .step-out { font-size:11px; color:var(--dim); margin-top:2px; word-break:break-all; }
    .step-out.collapsed { display:none; }
    .step-toggle { cursor:pointer; font-size:10px; color:var(--dim); margin-left:6px;
                   user-select:none; opacity:.7; }
    .step-toggle:hover { opacity:1; }
    .step-time { font-size:10px; color:var(--dim); margin-left:8px;
                 font-variant-numeric:tabular-nums; }
    .log-box { background:#0f172a; border:1px solid var(--border); border-radius:8px;
               padding:10px; font-size:12px; font-family:monospace; white-space:pre-wrap;
               max-height:160px; overflow-y:auto; margin-top:10px; display:none; }
    .result { margin-top:12px; padding:12px; border-radius:8px;
              background:var(--bg2); border:1px solid var(--ok); display:none; }
    .result-title { font-size:15px; font-weight:700; margin-bottom:6px; }
    .result-desc { font-size:12px; color:var(--dim); white-space:pre-wrap; max-height:110px;
                   overflow-y:auto; border:1px solid var(--border); border-radius:4px;
                   padding:8px; background:#0f172a; margin-bottom:8px; }
    .result-links { display:flex; flex-direction:column; gap:5px; }
    .result-links a { color:var(--link); font-size:13px; word-break:break-all; }
    .hint { font-size:11px; color:var(--dim); margin-left:8px; }
    hr { border:none; border-top:1px solid var(--border); margin:12px 0; }
    /* config */
    .config-toggle { cursor:pointer; color:var(--dim); font-size:12px; margin-bottom:8px; user-select:none; }
    .config-panel { display:none; padding:10px; border:1px solid var(--border);
                    border-radius:6px; background:var(--bg2); margin-bottom:12px; }
    .file-row { display:flex; gap:8px; align-items:flex-end; }
    .file-row input { flex:1; }
    .step-dl { font-size:11px; margin-top:4px; display:flex; gap:6px; flex-wrap:wrap; }
    .step-dl a { color:var(--link); text-decoration:none; padding:1px 7px;
                 border:1px solid var(--link); border-radius:4px; opacity:.85; }
    .step-dl a:hover { opacity:1; background:rgba(125,211,252,0.1); }
    /* resume area */
    .resume-area { display:none; margin-top:8px; padding:8px 10px;
                   border:1px solid var(--warn); border-radius:6px;
                   background:rgba(251,191,36,0.05); }
    .resume-area label { color:var(--warn); font-size:12px; margin-bottom:6px; }
    .resume-row { display:flex; gap:8px; align-items:center; flex-wrap:wrap; }
    .resume-row select { flex:1; min-width:180px; }
  </style>
</head>
<body>
<div class="wrap">
  <h2>🚀 Publish</h2>

  <!-- Config panel -->
  <div class="config-toggle" id="configToggle">⚙️ YouTube Publish Settings ▼</div>
  <div class="config-panel" id="configPanel">
    <div class="cols2">
      <div class="row">
        <label>Video source directory</label>
        <div class="file-row">
          <input type="text" id="sourceDir" placeholder="/home/joriel/Vidéos" />
          <button class="btn-sec" onclick="scanDir()">Scan</button>
        </div>
      </div>
      <div class="row">
        <label>File extensions (comma-separated)</label>
        <input type="text" id="videoExtensions" value="mp4,mkv" placeholder="mp4,mkv" />
      </div>
    </div>
    <div class="row">
      <label>Signature (appended to every description)</label>
      <textarea id="signature" rows="3" placeholder="Your signature / links..."></textarea>
    </div>
    <div class="row">
      <label>Post-publish script (bash script, called with final video path as argument)</label>
      <input type="text" id="postPublishScript" placeholder="/path/to/script.sh" />
    </div>
    <button class="btn-sec" onclick="saveConfig()">💾 Save settings</button>
    <span id="configStatus" style="font-size:12px;margin-left:8px;color:var(--ok);display:none">Saved!</span>
  </div>

  <div class="main-layout">
    <!-- Left: form -->
    <div class="main-left">
      <!-- Source video -->
      <div class="row">
        <label>Source video</label>
        <select id="fileSelect" onchange="onFileSelected()">
          <option value="">— select a video —</option>
        </select>
        <div id="dropZone" style="margin-top:6px;border:2px dashed var(--border);border-radius:6px;padding:12px;text-align:center;font-size:13px;color:var(--dim);cursor:pointer;">
          or drag &amp; drop external file here
        </div>
      </div>

      <!-- Prompts -->
      <div class="cols2">
        <div class="row">
          <label>Prompt — title</label>
          <input type="text" id="promptTitle" list="promptsList" placeholder="youtube-title" />
        </div>
        <div class="row">
          <label>Prompt — description</label>
          <input type="text" id="promptSummary" list="promptsList" placeholder="youtube-summary" />
        </div>
      </div>
      <datalist id="promptsList"></datalist>

      <!-- Description prefix -->
      <div class="row">
        <label>Description prefix (added at the top)</label>
        <textarea id="descPrefix" rows="2" placeholder="Optional text to prepend..."></textarea>
      </div>

      <!-- Source URLs -->
      <div class="row">
        <label>Source URLs (one per line — saved in meta)</label>
        <textarea id="sourceUrls" rows="2" placeholder="https://example.com/article&#10;https://youtube.com/watch?v=..."></textarea>
      </div>

      <!-- Options row -->
      <div class="cols2" style="align-items:flex-end">
        <div class="row" style="flex:0 0 auto">
          <label>Language</label>
          <input type="text" id="language" value="fr" style="width:55px" />
        </div>
        <div class="row" style="flex:0 0 auto">
          <label>Whisper model</label>
          <input type="text" id="model" value="medium" style="width:100px" />
        </div>
        <div class="row" style="flex:0 0 auto">
          <label>Privacy</label>
          <select id="privacy" style="width:100px">
            <option value="unlisted" selected>unlisted</option>
            <option value="private">private</option>
            <option value="public">public</option>
          </select>
        </div>
      </div>
      <div class="checkrow"><input type="checkbox" id="doSilence" checked /><span>Remove silence</span></div>
      <div class="checkrow"><input type="checkbox" id="doBurn" checked /><span>Burn subtitles</span></div>
      <div class="checkrow"><input type="checkbox" id="simpleTranscript" checked /><span>Simple transcript <span style="color:var(--dim);font-size:11px;">(no progress bar — timer only, use to measure real speed)</span></span></div>

      <!-- Action buttons -->
      <div style="margin-top:10px">
        <button class="btn-go" id="startBtn">▶ Publish</button>
      </div>

      <!-- Resume area — shown when a meta file exists for the selected source -->
      <div class="resume-area" id="resumeArea">
        <label>↩ Previous progress found — resume from:</label>
        <div class="resume-row">
          <select id="resumeFromStep"></select>
          <button class="btn-resume" id="resumeBtn">↩ Resume</button>
        </div>
      </div>
    </div>

    <!-- Right: video preview -->
    <div class="main-right">
      <div class="video-wrap" id="videoWrap">
        <video id="videoPreview" controls preload="metadata"></video>
        <div class="video-name" id="videoName"></div>
      </div>
    </div>
  </div>

  <hr />

  <div style="display:flex; align-items:center; gap:16px; margin-bottom:6px;">
    <div id="jobElapsed" style="display:none; font-size:12px; color:var(--dim);">
      Total: <span id="jobElapsedVal" style="color:var(--text); font-variant-numeric:tabular-nums;">0s</span>
    </div>
  </div>

  <div class="steps" id="stepsEl">
    <div class="step" id="step-0"><span class="step-icon">⬜</span><div style="flex:1"><div class="step-name">Remove silence<span class="step-time" id="time-0"></span><span class="step-toggle" id="toggle-0" onclick="toggleOut(0)">▶ logs</span></div><div class="step-out collapsed" id="out-0"></div><div class="step-dl" id="dl-0"></div></div></div>
    <div class="step" id="step-1"><span class="step-icon">⬜</span><div style="flex:1"><div class="step-name">Extract transcript<span class="step-time" id="time-1"></span></div><div class="step-out" id="out-1"></div><div class="step-dl" id="dl-1"></div></div></div>
    <div class="step" id="step-2"><span class="step-icon">⬜</span><div style="flex:1"><div class="step-name">Burn subtitles<span class="step-time" id="time-2"></span><span class="step-toggle" id="toggle-2" onclick="toggleOut(2)">▶ logs</span></div><div class="step-out collapsed" id="out-2"></div><div class="step-dl" id="dl-2"></div></div></div>
    <div class="step" id="step-3"><span class="step-icon">⬜</span><div style="flex:1"><div class="step-name">Generate title &amp; description<span class="step-time" id="time-3"></span></div><div class="step-out" id="out-3"></div></div></div>
    <div class="step" id="step-4"><span class="step-icon">⬜</span><div style="flex:1"><div class="step-name">Upload to YouTube<span class="step-time" id="time-4"></span></div><div class="step-out" id="out-4"></div></div></div>
  </div>

  <!-- Result -->
  <div class="result" id="result">
    <div class="result-title" id="resultTitle"></div>
    <div class="result-desc" id="resultDesc"></div>
    <div class="result-links">
      <a id="resultShortUrl" href="#" target="_blank"></a>
      <a id="resultStudioUrl" href="#" target="_blank"></a>
    </div>
  </div>
  <div class="log-box" id="logBox"></div>
</div>

<script>
const ICONS = { pending:'⬜', running:'🔄', done:'✅', error:'❌', skipped:'⏭️' };
const STEP_NAMES = ['Remove silence', 'Extract transcript', 'Burn subtitles', 'Generate title & description', 'Upload to YouTube'];
let pollTimer = null;
let elapsedTimer = null;
let jobId = null;
let selectedFilePath = '';
let _jobStartTime = null;
let _stepStartTimes = [null, null, null, null, null]; // server unix timestamps for running steps

function _fmtSec(s) {
  s = Math.round(s);
  if (s < 60) return s + 's';
  const m = Math.floor(s / 60), r = s % 60;
  return m + 'm ' + (r > 0 ? r + 's' : '');
}

function _tickElapsed() {
  const now = Date.now() / 1000;
  if (_jobStartTime) {
    const el = document.getElementById('jobElapsedVal');
    if (el) el.textContent = _fmtSec(now - _jobStartTime);
  }
  _stepStartTimes.forEach((t, i) => {
    if (t === null) return;
    const el = document.getElementById('time-' + i);
    if (el && el.dataset.running === '1') {
      el.textContent = ' ⏱ ' + _fmtSec(now - t);
    }
  });
}

function _startElapsedTimer() {
  if (!elapsedTimer) elapsedTimer = setInterval(_tickElapsed, 1000);
}
function _stopElapsedTimer() {
  if (elapsedTimer) { clearInterval(elapsedTimer); elapsedTimer = null; }
}

// ── Config ────────────────────────────────────────────────────────────────────

document.getElementById('configToggle').addEventListener('click', () => {
  const panel = document.getElementById('configPanel');
  const toggle = document.getElementById('configToggle');
  const open = panel.style.display === 'block';
  panel.style.display = open ? 'none' : 'block';
  toggle.textContent = '⚙️ YouTube Publish Settings ' + (open ? '▼' : '▲');
});

async function loadConfig() {
  const r = await fetch('/api/publish/config').catch(() => null);
  if (!r || !r.ok) return;
  const data = await r.json();
  document.getElementById('sourceDir').value = data.video_source_path || '/home/joriel/Vidéos';
  document.getElementById('videoExtensions').value = data.video_extensions || 'mp4,mkv';
  document.getElementById('signature').value = data.signature || '';
  document.getElementById('postPublishScript').value = data.post_publish_script || '';
  await scanDir();
}

async function saveConfig() {
  const r = await fetch('/api/publish/config', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      video_source_path: document.getElementById('sourceDir').value.trim(),
      video_extensions: document.getElementById('videoExtensions').value.trim() || 'mp4,mkv',
      signature: document.getElementById('signature').value,
      post_publish_script: document.getElementById('postPublishScript').value.trim(),
    }),
  }).catch(() => null);
  const st = document.getElementById('configStatus');
  st.style.display = 'inline';
  if (r && r.ok) {
    st.textContent = 'Saved!';
    st.style.color = 'var(--ok)';
  } else {
    st.textContent = 'Error saving';
    st.style.color = 'var(--err)';
  }
  setTimeout(() => { st.style.display = 'none'; }, 2000);
}

// ── Video list ─────────────────────────────────────────────────────────────────

async function scanDir() {
  const dir = document.getElementById('sourceDir').value.trim() || '/home/joriel/Vidéos';
  const ext = document.getElementById('videoExtensions').value.trim() || 'mp4,mkv';
  const r = await fetch(
    '/api/publish/list-videos?path=' + encodeURIComponent(dir) + '&extensions=' + encodeURIComponent(ext)
  ).catch(() => null);
  const sel = document.getElementById('fileSelect');
  sel.innerHTML = '<option value="">— select a video —</option>';
  if (!r || !r.ok) return;
  const data = await r.json();
  if (data.videos && data.videos.length) {
    data.videos.forEach(v => {
      const opt = document.createElement('option');
      opt.value = v.path;
      opt.textContent = v.name;
      sel.appendChild(opt);
    });
    sel.value = data.videos[0].path;
    onFileSelected();
  }
}

function onFileSelected() {
  const path = document.getElementById('fileSelect').value;
  selectedFilePath = path;
  const wrap = document.getElementById('videoWrap');
  const video = document.getElementById('videoPreview');
  const nameEl = document.getElementById('videoName');
  if (path) {
    video.src = '/api/publish/video-preview?file=' + encodeURIComponent(path);
    nameEl.textContent = path.split('/').pop();
    wrap.style.display = 'block';
    checkResume();
  } else {
    wrap.style.display = 'none';
    video.src = '';
    nameEl.textContent = '';
    document.getElementById('resumeArea').style.display = 'none';
  }
}

// ── Prompts ────────────────────────────────────────────────────────────────────

async function loadPrompts() {
  const r = await fetch('/api/publish/list-prompts').catch(() => null);
  if (!r || !r.ok) return;
  const data = await r.json();
  const prompts = data.prompts || [];
  const dl = document.getElementById('promptsList');
  dl.innerHTML = '';
  prompts.forEach(name => {
    const opt = document.createElement('option');
    opt.value = name;
    dl.appendChild(opt);
  });
  const ptEl = document.getElementById('promptTitle');
  const psEl = document.getElementById('promptSummary');
  if (!ptEl.value && prompts.includes('youtube-title'))   ptEl.value = 'youtube-title';
  if (!psEl.value && prompts.includes('youtube-summary')) psEl.value = 'youtube-summary';
}

// ── Resume check ──────────────────────────────────────────────────────────────

async function checkResume() {
  const src = selectedFilePath || document.getElementById('fileSelect').value;
  const area = document.getElementById('resumeArea');

  // Always clear previous resume state first
  for (let i = 0; i < 5; i++) {
    const icon = document.querySelector('#step-' + i + ' .step-icon');
    if (icon) icon.textContent = '⬜';
    const dlEl = document.getElementById('dl-' + i);
    if (dlEl) dlEl.innerHTML = '';
  }

  if (!src) { area.style.display = 'none'; return; }

  const r = await fetch('/api/publish/check-resume', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ source: src }),
  }).catch(() => null);

  if (!r || !r.ok) { area.style.display = 'none'; return; }
  const data = await r.json();

  // Show step icons and download links for previously completed/skipped steps
  (data.completed_steps || []).forEach(i => {
    const icon = document.querySelector('#step-' + i + ' .step-icon');
    if (icon) icon.textContent = '✅';
  });
  (data.skipped_steps || []).forEach(i => {
    const icon = document.querySelector('#step-' + i + ' .step-icon');
    if (icon) icon.textContent = '⏭️';
  });
  (data.step_files || []).forEach((files, i) => {
    const dlEl = document.getElementById('dl-' + i);
    if (dlEl && files.length) {
      dlEl.innerHTML = files.map(f =>
        `<a href="/api/publish/download?file=${encodeURIComponent(f.path)}" download="${f.name}">⬇ ${f.name}</a>`
      ).join('');
    }
  });

  if (!data.can_resume || !data.available_from_steps.length) {
    area.style.display = 'none';
    return;
  }

  const sel = document.getElementById('resumeFromStep');
  sel.innerHTML = '';
  const steps = [...data.available_from_steps].reverse();
  steps.forEach(step => {
    const opt = document.createElement('option');
    opt.value = step;
    const doneLabel = step < STEP_NAMES.length ? STEP_NAMES[step] : '?';
    const skipList = Array.from({length: step}, (_, i) => STEP_NAMES[i]).join(', ');
    opt.textContent = `Step ${step + 1}: ${doneLabel}` + (step > 0 ? ` (reuse: ${skipList})` : '');
    sel.appendChild(opt);
  });
  sel.value = steps[0];

  area.style.display = 'block';
}

// ── Pipeline UI ────────────────────────────────────────────────────────────────

function renderSteps(steps) {
  steps.forEach((s, i) => {
    const icon   = document.querySelector('#step-' + i + ' .step-icon');
    const out    = document.getElementById('out-' + i);
    const nameEl = document.querySelector('#step-' + i + ' .step-name');
    const timeEl = document.getElementById('time-' + i);
    if (icon) icon.textContent = ICONS[s.status] || '⬜';
    if (out)  out.textContent  = s.output || '';

    // Progress bar
    if (nameEl) {
      let bar = nameEl.querySelector('.step-progress');
      if (s.progress != null) {
        if (!bar) {
          bar = document.createElement('progress');
          bar.className = 'step-progress';
          bar.max = 100;
          // Insert before toggle span if present, else append
          const toggle = nameEl.querySelector('.step-toggle');
          toggle ? nameEl.insertBefore(bar, toggle) : nameEl.appendChild(bar);
        }
        bar.value = s.progress;
      } else if (bar) {
        bar.remove();
      }
    }

    // Download links (steps 0-2 only)
    const dlEl = document.getElementById('dl-' + i);
    if (dlEl) {
      if (s.status === 'done' && s.output_files && s.output_files.length) {
        dlEl.innerHTML = s.output_files.map(f =>
          `<a href="/api/publish/download?file=${encodeURIComponent(f.path)}" download="${f.name}">⬇ ${f.name}</a>`
        ).join('');
      }
    }

    // Elapsed time label
    if (timeEl) {
      if (s.status === 'running' && s.start_time) {
        _stepStartTimes[i] = s.start_time;
        timeEl.dataset.running = '1';
        timeEl.textContent = ' ⏱ ' + _fmtSec(Date.now()/1000 - s.start_time);
      } else if ((s.status === 'done' || s.status === 'error') && s.elapsed_seconds != null) {
        _stepStartTimes[i] = null;
        timeEl.dataset.running = '0';
        timeEl.textContent = ' (' + _fmtSec(s.elapsed_seconds) + ')';
      } else if (s.status === 'pending' || s.status === 'skipped') {
        _stepStartTimes[i] = null;
        timeEl.dataset.running = '0';
        timeEl.textContent = '';
      }
    }
  });
}

function toggleOut(i) {
  const out = document.getElementById('out-' + i);
  const tog = document.getElementById('toggle-' + i);
  if (!out || !tog) return;
  const willCollapse = !out.classList.contains('collapsed');
  out.classList.toggle('collapsed');
  tog.textContent = willCollapse ? '▶ logs' : '▼ logs';
}

function log(msg) {
  const box = document.getElementById('logBox');
  box.style.display = 'block';
  box.textContent += msg + '\\n';
  box.scrollTop = box.scrollHeight;
}

function stopPoll() { if (pollTimer) { clearInterval(pollTimer); pollTimer = null; } }

function resetUI() {
  stopPoll(); _stopElapsedTimer();
  jobId = null; _jobStartTime = null; _stepStartTimes = [null,null,null,null,null];
  document.getElementById('result').style.display    = 'none';
  document.getElementById('logBox').style.display    = 'none';
  document.getElementById('logBox').textContent      = '';
  document.getElementById('jobElapsed').style.display = 'none';
  for (let i = 0; i < 5; i++) {
    document.querySelector('#step-' + i + ' .step-icon').textContent = '⬜';
    const out = document.getElementById('out-' + i);
    out.textContent = '';
    const timeEl = document.getElementById('time-' + i);
    if (timeEl) { timeEl.textContent = ''; timeEl.dataset.running = '0'; }
    const nameEl = document.querySelector('#step-' + i + ' .step-name');
    if (nameEl) { const bar = nameEl.querySelector('.step-progress'); if (bar) bar.remove(); }
    const dlEl = document.getElementById('dl-' + i);
    if (dlEl) dlEl.innerHTML = '';
    if (i === 0 || i === 2) {
      out.classList.add('collapsed');
      const tog = document.getElementById('toggle-' + i);
      if (tog) tog.textContent = '▶ logs';
    }
  }
}

async function poll() {
  if (!jobId) return;
  const r = await fetch('/api/publish/status/' + jobId).catch(() => null);
  if (!r || !r.ok) return;
  const data = await r.json();

  // Total elapsed
  if (data.start_time) {
    _jobStartTime = data.start_time;
    const elDiv = document.getElementById('jobElapsed');
    elDiv.style.display = 'block';
    if (data.status !== 'running') {
      // Fixed: show final elapsed
      document.getElementById('jobElapsedVal').textContent = _fmtSec(data.elapsed_seconds || 0);
    }
  }

  renderSteps(data.steps);

  if (data.status === 'running') {
    _startElapsedTimer();
  }

  if (data.status === 'done') {
    stopPoll(); _stopElapsedTimer();
    document.getElementById('startBtn').disabled = false;
    document.getElementById('resumeBtn').disabled = false;
    const res = document.getElementById('result');
    document.getElementById('resultTitle').textContent = '✅ ' + (data.title || 'Published!');
    document.getElementById('resultDesc').textContent  = data.description || '';
    const shortEl  = document.getElementById('resultShortUrl');
    const studioEl = document.getElementById('resultStudioUrl');
    if (data.video_url) { shortEl.href = data.video_url; shortEl.textContent = '📱 ' + data.video_url; }
    if (data.studio_url) { studioEl.href = data.studio_url; studioEl.textContent = '📊 ' + data.studio_url; }
    res.style.display = 'block';
    checkResume();
  } else if (data.status === 'error') {
    stopPoll(); _stopElapsedTimer();
    document.getElementById('startBtn').disabled = false;
    document.getElementById('resumeBtn').disabled = false;
    checkResume();
  }
}

async function launch(isResume) {
  const src  = selectedFilePath || document.getElementById('fileSelect').value;
  const pt   = document.getElementById('promptTitle').value.trim();
  const ps   = document.getElementById('promptSummary').value.trim();
  const priv = document.getElementById('privacy').value;
  const desc_prefix = document.getElementById('descPrefix').value;
  if (!src)       { alert('Select a source video.'); return; }
  if (!pt || !ps) { alert('Fill in both prompt names.'); return; }

  resetUI();
  document.getElementById('startBtn').disabled = true;
  document.getElementById('resumeBtn').disabled = true;

  const source_urls = document.getElementById('sourceUrls').value
    .split('\\n').map(u => u.trim()).filter(u => u.startsWith('http'));

  let url, body;
  if (isResume) {
    const fromStep = parseInt(document.getElementById('resumeFromStep').value, 10);
    url = '/api/publish/resume';
    body = {
      source: src, prompt_title: pt, prompt_summary: ps, privacy: priv,
      description_prefix: desc_prefix, source_urls,
      from_step: fromStep,
      do_burn_subtitles: document.getElementById('doBurn').checked,
      simple_transcript: document.getElementById('simpleTranscript').checked,
      language: document.getElementById('language').value.trim() || 'fr',
      model:    document.getElementById('model').value.trim()    || 'medium',
    };
  } else {
    url = '/api/publish/start';
    body = {
      source: src, prompt_title: pt, prompt_summary: ps, privacy: priv,
      description_prefix: desc_prefix, source_urls,
      do_remove_silence: document.getElementById('doSilence').checked,
      do_burn_subtitles: document.getElementById('doBurn').checked,
      simple_transcript: document.getElementById('simpleTranscript').checked,
      language: document.getElementById('language').value.trim() || 'fr',
      model:    document.getElementById('model').value.trim()    || 'medium',
    };
  }

  const r = await fetch(url, {
    method: 'POST', headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  }).catch(e => {
    log('Error: ' + e.message);
    document.getElementById('startBtn').disabled = false;
    document.getElementById('resumeBtn').disabled = false;
    return null;
  });
  if (!r) return;
  if (!r.ok) {
    const err = await r.json().catch(() => ({ detail: 'Failed' }));
    log('Error: ' + (err.detail || 'Failed'));
    document.getElementById('startBtn').disabled = false;
    document.getElementById('resumeBtn').disabled = false;
    return;
  }
  const data = await r.json();
  jobId = data.job_id;
  log('Job: ' + jobId);
  pollTimer = setInterval(poll, 2000);
}

document.getElementById('startBtn').addEventListener('click', () => launch(false));
document.getElementById('resumeBtn').addEventListener('click', () => launch(true));

// ── Init ───────────────────────────────────────────────────────────────────────

loadConfig();
loadPrompts();

// ── Drag & drop external upload ───────────────────────────────────────────────

const dropZone = document.getElementById('dropZone');
dropZone.addEventListener('click', () => {
  const inp = document.createElement('input');
  inp.type = 'file';
  inp.accept = 'video/*';
  inp.onchange = () => { if (inp.files[0]) uploadExternal(inp.files[0]); };
  inp.click();
});
dropZone.addEventListener('dragover', e => { e.preventDefault(); dropZone.style.borderColor = 'var(--accent)'; });
dropZone.addEventListener('dragleave', () => { dropZone.style.borderColor = 'var(--border)'; });
dropZone.addEventListener('drop', e => {
  e.preventDefault();
  dropZone.style.borderColor = 'var(--border)';
  if (e.dataTransfer.files.length) uploadExternal(e.dataTransfer.files[0]);
});

async function uploadExternal(file) {
  const fd = new FormData();
  fd.append('file', file);
  const r = await fetch('/api/publish/upload-external', { method: 'POST', body: fd }).catch(() => null);
  if (!r || !r.ok) { alert('Upload failed'); return; }
  const data = await r.json();
  const sel = document.getElementById('fileSelect');
  const opt = document.createElement('option');
  opt.value = data.path;
  opt.textContent = data.name + ' (uploaded)';
  sel.appendChild(opt);
  sel.value = data.path;
  onFileSelected();
}
</script>
</body>
</html>
"""


def register(config: dict) -> WebuxPluginManifest:
    del config
    return WebuxPluginManifest(
        name="publish",
        tab_label="Publish",
        tab_icon="🚀",
        api_router=router,
        frontend_html=_HTML,
        order=45,
        lazy=True,
    )
