[alembic]
script_location = %(here)s/storage/migrations
sqlalchemy.url = sqlite+pysqlite:///~/.local/share/fast-market/profiles/default/rag/rag.db

[loggers]
keys = root

[handlers]
keys =

[formatters]
keys =

[logger_root]
level = WARN
handlers =
