from __future__ import annotations

import os
import click
from pathlib import Path

from commands.completion import ShellType
from commands.discovery import discover_fastmarket_commands


def _get_config_dir() -> Path:
    """Get XDG config home / fast-market directory."""
    xdg_config = os.environ.get("XDG_CONFIG_HOME", str(Path.home() / ".config"))
    return Path(xdg_config) / "fast-market"


def register():
    """Return the 'autocomplete' command group with configure + list subcommands."""
    @click.group(
        "autocomplete",
        help="Manage shell autocompletion for fast-market CLI tools.",
    )
    def autocomplete_group():
        """Autocompletion management."""
        pass

    @autocomplete_group.command("configure")
    @click.option(
        "--shell",
        "-s",
        type=ShellType(),
        default="bash",
        help="Shell type",
    )
    @click.option("--force", "-f", is_flag=True, help="Regenerate completion files")
    def configure(shell: str, force: bool):
        """Generate shell completion script for all discovered fast-market CLIs."""
        tools = discover_fastmarket_commands()

        config_dir = _get_config_dir()
        completions_dir = config_dir / "completions"
        completions_dir.mkdir(parents=True, exist_ok=True)
        completion_file = completions_dir / f"fast-market.{shell}"

        if completion_file.exists() and not force:
            existing_content = completion_file.read_text().strip()
            desired_lines = _generate_completion_script(shell, tools)
            desired_content = "\n".join(desired_lines).strip()

            if existing_content == desired_content:
                click.echo(f"Completions already configured for: {', '.join(tools)}")
                click.echo(f"File: {completion_file}")
                click.echo("\nTo regenerate (e.g. after adding/removing a *-cli), run with --force")
                return
            else:
                click.echo("Completions file is out of date.")
                click.echo("It contains stale entries (e.g. removed CLIs like tiktok) or is missing newly added CLIs.")
                click.echo(f"File: {completion_file}")
                click.echo("Run with --force to regenerate a clean file for the current set of tools.")
                return

        click.echo(f"Generating completions for: {', '.join(tools)}")

        lines = _generate_completion_script(shell, tools)
        completion_file.write_text("\n".join(lines))

        click.echo(f"\nCompletions saved to: {completion_file}")

        if shell == "bash":
            click.echo("\nAdd this to your ~/.bashrc:")
            click.echo(f"  source {completion_file}")
        elif shell == "zsh":
            click.echo("\nAdd this to your ~/.zshrc:")
            click.echo(f"  source {completion_file}")
        elif shell == "fish":
            click.echo("\nAdd this to your ~/.config/fish/config.fish:")
            click.echo(f"  source {completion_file}")

        click.echo(
            "\nOr run the source command above to enable completions immediately."
        )

    @autocomplete_group.command("list")
    def list_cmd():
        """List all currently discovered fast-market CLI command names."""
        for name in discover_fastmarket_commands():
            click.echo(name)

    return autocomplete_group


def _generate_completion_script(shell: str, tools: list[str]) -> list[str]:
    lines = []
    lines.append("# Fast-market shell completions")
    lines.append("# Generated by toolsetup autocomplete configure")
    lines.append("")

    for tool in tools:
        if shell == "bash":
            lines.append(f'eval "$(_{tool.upper()}_COMPLETE=bash_source {tool})"')
        elif shell == "zsh":
            lines.append(f'eval "$(_{tool.upper()}_COMPLETE=zsh_source {tool})"')
        elif shell == "fish":
            env_var = f"_{tool.upper()}_COMPLETE"
            lines.append(f"eval ({env_var}=fish_source {tool})")

    return lines


def get_registered_tools() -> list[str]:
    """Return the live list of discovered fast-market CLI commands."""
    return discover_fastmarket_commands()
