from __future__ import annotations

import os
import click
from pathlib import Path

from commands.completion import ShellType

_TOOLS = [
    "corpus",
    "image",
    "message",
    "monitor",
    "prompt",
    "skill",
    "task",
    "tiktok",
    "toolsetup",
    "youtube",
]


def _get_config_dir() -> Path:
    """Get XDG config home / fast-market directory."""
    xdg_config = os.environ.get("XDG_CONFIG_HOME", str(Path.home() / ".config"))
    return Path(xdg_config) / "fast-market"


def register():
    @click.command("autocomplete-configure")
    @click.option(
        "--shell",
        "-s",
        type=ShellType(),
        default="bash",
        help="Shell type",
    )
    @click.option("--force", "-f", is_flag=True, help="Regenerate completion files")
    def autocomplete_configure(shell: str, force: bool):
        """Configure shell autocompletion for all fast-market CLI tools.

        This command generates completion scripts and saves them to a single
        file that you can source from your shell configuration.
        """
        config_dir = _get_config_dir()
        completions_dir = config_dir / "completions"
        completions_dir.mkdir(parents=True, exist_ok=True)
        completion_file = completions_dir / f"fast-market.{shell}"

        existing_tools = []
        if completion_file.exists() and not force:
            content = completion_file.read_text()
            for tool in _TOOLS:
                if f"_COMPLETE=bash_source {tool}" in content:
                    existing_tools.append(tool)

        if existing_tools:
            click.echo(
                f"Completions already configured for: {', '.join(existing_tools)}"
            )
            click.echo(f"File: {completion_file}")
            click.echo("\nTo regenerate, run with --force")
            return

        click.echo(f"Generating completions for: {', '.join(_TOOLS)}")

        lines = _generate_completion_script(shell)
        completion_file.write_text("\n".join(lines))

        click.echo(f"\nCompletions saved to: {completion_file}")

        if shell == "bash":
            click.echo("\nAdd this to your ~/.bashrc:")
            click.echo(f"  source {completion_file}")
        elif shell == "zsh":
            click.echo("\nAdd this to your ~/.zshrc:")
            click.echo(f"  source {completion_file}")
        elif shell == "fish":
            click.echo("\nAdd this to your ~/.config/fish/config.fish:")
            click.echo(f"  source {completion_file}")

        click.echo(
            "\nOr run the source command above to enable completions immediately."
        )

    return autocomplete_configure


def _generate_completion_script(shell: str) -> list[str]:
    lines = []
    lines.append("# Fast-market shell completions")
    lines.append(f"# Generated by toolsetup autocomplete-configure")
    lines.append("")

    for tool in _TOOLS:
        if shell == "bash":
            lines.append(f'eval "$(_{tool.upper()}_COMPLETE=bash_source {tool})"')
        elif shell == "zsh":
            lines.append(f'eval "$(_{tool.upper()}_COMPLETE=zsh_source {tool})"')
        elif shell == "fish":
            lines.append(f"_{tool}_complete | source /dev/stdin")

    return lines


def get_registered_tools() -> list[str]:
    return _TOOLS
