from __future__ import annotations

import os

import click
from pathlib import Path

from commands.base import CommandManifest
from commands.completion import ShellType

_TOOLS = [
    "social",
]


def _get_config_dir() -> Path:
    """Get XDG config home / social directory."""
    xdg_config = os.environ.get("XDG_CONFIG_HOME", str(Path.home() / ".config"))
    return Path(xdg_config) / "social"


def _generate_completion_script(shell: str) -> list[str]:
    lines = ["# Social CLI shell completions", "# Generated by social autocomplete-configure", ""]
    for tool in _TOOLS:
        if shell == "bash":
            lines.append(f'eval "$(_{tool.upper()}_COMPLETE=bash_source {tool})"')
        elif shell == "zsh":
            lines.append(f'eval "$(_{tool.upper()}_COMPLETE=zsh_source {tool})"')
        elif shell == "fish":
            lines.append(f"_{tool}_complete | source /dev/stdin")
    return lines


def register(plugin_manifests: dict) -> CommandManifest:
    @click.command("autocomplete-configure")
    @click.option(
        "--shell",
        "-s",
        type=ShellType(),
        default="bash",
        help="Shell type to generate completions for.",
    )
    @click.option("--force", "-f", is_flag=True, help="Overwrite existing completion file.")
    def autocomplete_configure(shell: str, force: bool):
        """Configure shell autocompletion for the social CLI."""
        config_dir = _get_config_dir()
        completions_dir = config_dir / "completions"
        completions_dir.mkdir(parents=True, exist_ok=True)
        completion_file = completions_dir / f"social.{shell}"

        if completion_file.exists() and not force:
            click.echo(f"Completions already configured: {completion_file}")
            click.echo("To regenerate, run with --force")
            return

        lines = _generate_completion_script(shell)
        completion_file.write_text("\n".join(lines) + "\n")

        click.echo(f"Completions saved to: {completion_file}")

        if shell == "bash":
            click.echo(f"\nAdd to your ~/.bashrc:\n  source {completion_file}")
        elif shell == "zsh":
            click.echo(f"\nAdd to your ~/.zshrc:\n  source {completion_file}")
        elif shell == "fish":
            click.echo(f"\nAdd to your ~/.config/fish/config.fish:\n  source {completion_file}")

        click.echo("\nOr run the source command above to enable completions immediately.")

    return CommandManifest(
        name="autocomplete-configure",
        click_command=autocomplete_configure,
    )
